title: Radim Oliva
theme: minima
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: page
      is_project: true

exclude_from_posts:
  - "_projects/**"
